using System.Linq;

namespace VisCPU.Utility
{
    public struct AddressItem
    {
        public bool AutoGenerated => LinkerArguments.Contains("linker:autogen");

        public bool Hide => LinkerArguments.Contains("linker:hide");

        public uint Address;
        public object[] LinkerArguments;

        public AddressItem Offset(uint off)
        {
            return new AddressItem
            {
                Address = Address + off,
                LinkerArguments = LinkerArguments
            };
        }
    }
}